### ISSUE TITLE
Initial relase

### ISSUE THREAD

**Issue by spekulatius** [Graphiques-Digitale/silverstripe-seo-icons#2]
Hello @4t4r1 

thank you for the great set of modules :) Could you tag an initial release for the seo-icons?

Cheers,
Peter

**Comment by 4t4r1** [comment]
Tagged v1.0.0 @ https://github.com/Graphiques-Digitale/silverstripe-seo-icons/tree/v1.0.0

**Comment by spekulatius** [comment]
Thank you :)
